name: mcal
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.11
  - aiosignal=1.3.2
  - alsa-lib=1.2.13
  - aom=3.9.1
  - async-timeout=5.0.1
  - attr=2.5.1
  - attrs=24.3.0
  - blosc=1.21.6
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2024.12.14
  - cairo=1.18.2
  - certifi=2024.12.14
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - colour=0.1.5
  - contourpy=1.3.0
  - cycler=0.12.1
  - cyrus-sasl=2.1.27
  - dav1d=1.2.1
  - dbus=1.13.6
  - double-conversion=3.3.0
  - expat=2.6.4
  - ffmpeg=7.1.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.55.3
  - freetype=2.12.1
  - fribidi=1.0.10
  - frozenlist=1.5.0
  - gdk-pixbuf=2.42.12
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gl2ps=1.4.2
  - glew=2.1.0
  - glib=2.82.2
  - glib-tools=2.82.2
  - gmp=6.3.0
  - graphite2=1.3.13
  - gst-plugins-base=1.24.7
  - gstreamer=1.24.7
  - h2=4.1.0
  - harfbuzz=10.1.0
  - hdf4=4.2.15
  - hdf5=1.14.3
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=75.1
  - idna=3.10
  - imageio=2.36.1
  - importlib-resources=6.5.2
  - importlib_resources=6.5.2
  - jsoncpp=1.9.6
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - level-zero=1.19.2
  - libabseil=20240722.0
  - libaec=1.1.3
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libass=0.17.3
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.71
  - libcblas=3.9.0
  - libclang-cpp19.1=19.1.6
  - libclang13=19.1.6
  - libcups=2.3.3
  - libcurl=8.11.1
  - libdeflate=1.23
  - libdrm=2.4.124
  - libedit=3.1.20240808
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.4
  - libffi=3.4.2
  - libflac=1.4.3
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgcrypt-lib=1.11.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libgl=1.7.0
  - libglib=2.82.2
  - libglu=9.0.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=14.2.0
  - libgpg-error=1.51
  - libhwloc=2.11.2
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libllvm19=19.1.6
  - liblzma=5.6.3
  - libnetcdf=4.9.2
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libogg=1.3.5
  - libopenblas=0.3.28
  - libopenvino=2024.6.0
  - libopenvino-auto-batch-plugin=2024.6.0
  - libopenvino-auto-plugin=2024.6.0
  - libopenvino-hetero-plugin=2024.6.0
  - libopenvino-intel-cpu-plugin=2024.6.0
  - libopenvino-intel-gpu-plugin=2024.6.0
  - libopenvino-intel-npu-plugin=2024.6.0
  - libopenvino-ir-frontend=2024.6.0
  - libopenvino-onnx-frontend=2024.6.0
  - libopenvino-paddle-frontend=2024.6.0
  - libopenvino-pytorch-frontend=2024.6.0
  - libopenvino-tensorflow-frontend=2024.6.0
  - libopenvino-tensorflow-lite-frontend=2024.6.0
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.45
  - libpq=17.2
  - libprotobuf=5.28.3
  - librsvg=2.58.4
  - libsndfile=1.2.2
  - libsqlite=3.47.2
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libsystemd0=257.2
  - libtheora=1.1.1
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libva=2.22.0
  - libvorbis=1.3.7
  - libvpx=1.14.1
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.7.0
  - libxml2=2.13.5
  - libzip=1.11.2
  - libzlib=1.3.1
  - loguru=0.7.2
  - lz4-c=1.10.0
  - matplotlib-base=3.9.4
  - mpg123=1.32.9
  - msgpack-python=1.1.0
  - multidict=6.1.0
  - munkres=1.1.4
  - mysql-common=9.0.1
  - mysql-libs=9.0.1
  - ncurses=6.5
  - nlohmann_json=3.11.3
  - nspr=4.36
  - nss=3.107
  - ocl-icd=2.3.2
  - opencl-headers=2024.10.24
  - openh264=2.5.0
  - openjpeg=2.5.3
  - openldap=2.6.9
  - openssl=3.4.0
  - packaging=24.2
  - pango=1.54.0
  - pcre2=10.44
  - pillow=11.1.0
  - pip=24.3.1
  - pixman=0.44.2
  - platformdirs=4.3.6
  - ply=3.11
  - pooch=1.8.2
  - proj=9.5.1
  - propcache=0.2.1
  - pthread-stubs=0.4
  - pugixml=1.14
  - pulseaudio-client=17.0
  - pycparser=2.22
  - pyparsing=3.2.1
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pysocks=1.7.1
  - python=3.9.21
  - python-dateutil=2.9.0.post0
  - python_abi=3.9
  - pyvista=0.44.2
  - pyvistaqt=0.11.1
  - qhull=2020.2
  - qt-main=5.15.15
  - qt6-main=6.8.1
  - qtawesome=1.3.1
  - qtpy=2.4.2
  - readline=8.2
  - requests=2.32.3
  - scooby=0.10.0
  - setuptools=75.6.0
  - sip=6.7.12
  - six=1.17.0
  - snappy=1.2.1
  - sqlite=3.47.2
  - svt-av1=2.3.0
  - tbb=2022.0.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.2.1
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024b
  - unicodedata2=15.1.0
  - urllib3=2.3.0
  - utfcpp=4.0.6
  - vtk=9.3.1
  - vtk-base=9.3.1
  - vtk-io-ffmpeg=9.3.1
  - wayland=1.23.1
  - wayland-protocols=1.37
  - wheel=0.45.1
  - wslink=2.2.2
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.43
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.5
  - xorg-libx11=1.8.10
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxt=1.3.1
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - yarl=1.18.3
  - zipp=3.21.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - antlr4-python3-runtime==4.9.3
      - cached-property==2.0.1
      - docstring-parser==0.16
      - llvmlite==0.43.0
      - multical==0.2.1
      - natsort==8.4.0
      - numba==0.60.0
      - numpy==1.26.4
      - numpy-quaternion==2023.0.4
      - omegaconf==2.3.0
      - opencv-contrib-python==4.10.0.84
      - palettable==3.3.3
      - py-structs==0.2.14
      - pyyaml==6.0.2
      - scipy==1.13.1
      - simple-parsing==0.1.6
      - tqdm==4.67.1
